//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolEntities1 : DbContext
    {
        public SchoolEntities1()
            : base("name=SchoolEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ДолжностьРаботы> ДолжностьРаботы { get; set; }
        public virtual DbSet<ДолжностьШколы> ДолжностьШколы { get; set; }
        public virtual DbSet<ЖурналДолжностей> ЖурналДолжностей { get; set; }
        public virtual DbSet<ЖурналПосещаемости> ЖурналПосещаемости { get; set; }
        public virtual DbSet<ЖурналУспеваемости> ЖурналУспеваемости { get; set; }
        public virtual DbSet<Класс> Класс { get; set; }
        public virtual DbSet<МестоРаботы> МестоРаботы { get; set; }
        public virtual DbSet<Отметка> Отметка { get; set; }
        public virtual DbSet<Предмет> Предмет { get; set; }
        public virtual DbSet<Преподаватель> Преподаватель { get; set; }
        public virtual DbSet<Родители> Родители { get; set; }
        public virtual DbSet<Ученик> Ученик { get; set; }
    }
}
