//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЖурналУспеваемости
    {
        public int КодЖурнала { get; set; }
        public Nullable<int> КодУченика { get; set; }
        public Nullable<int> КодПреподавателя { get; set; }
        public Nullable<int> КодПредмета { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Оценка { get; set; }
    
        public virtual Предмет Предмет { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
        public virtual Ученик Ученик { get; set; }
    }
}
