//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЖурналДолжностей
    {
        public int КодЖурнала { get; set; }
        public Nullable<int> КодПреподавателя { get; set; }
        public Nullable<int> КодДолжности { get; set; }
        public Nullable<System.DateTime> ДатаПринятия { get; set; }
        public Nullable<System.DateTime> ДатаСнятия { get; set; }
    
        public virtual ДолжностьШколы ДолжностьШколы { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
    }
}
