//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class МестоРаботы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public МестоРаботы()
        {
            this.Родители = new HashSet<Родители>();
        }
    
        public int КодРаботы { get; set; }
        public string Название { get; set; }
        public Nullable<int> КодДолжности { get; set; }
        public string ТелефонОрганизации { get; set; }
        public string ЭлектроннаяПочтаОрганизации { get; set; }
    
        public virtual ДолжностьРаботы ДолжностьРаботы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Родители> Родители { get; set; }
    }
}
