//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватель
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Преподаватель()
        {
            this.ЖурналДолжностей = new HashSet<ЖурналДолжностей>();
            this.ЖурналПосещаемости = new HashSet<ЖурналПосещаемости>();
            this.ЖурналУспеваемости = new HashSet<ЖурналУспеваемости>();
        }
    
        public int КодПреподавателя { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string НомерТелефона { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖурналДолжностей> ЖурналДолжностей { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖурналПосещаемости> ЖурналПосещаемости { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖурналУспеваемости> ЖурналУспеваемости { get; set; }
    }
}
