//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Родители
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Родители()
        {
            this.Ученик = new HashSet<Ученик>();
        }
    
        public int КодРодителя { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string НомерТелефона { get; set; }
        public Nullable<int> КодМестаРаботы { get; set; }
        public Nullable<int> КодДолжности { get; set; }
    
        public virtual ДолжностьРаботы ДолжностьРаботы { get; set; }
        public virtual МестоРаботы МестоРаботы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ученик> Ученик { get; set; }
    }
}
