//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolDBwpf.SqlData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ученик
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ученик()
        {
            this.ЖурналПосещаемости = new HashSet<ЖурналПосещаемости>();
            this.ЖурналУспеваемости = new HashSet<ЖурналУспеваемости>();
        }
    
        public int КодУченика { get; set; }
        public string ФИОУченика { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string НомерСвидетельстваОРождении { get; set; }
        public string НомерРегистрацииРебенка { get; set; }
        public string НомерСнилса { get; set; }
        public Nullable<int> КодРодителя { get; set; }
        public Nullable<int> КодКласса { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖурналПосещаемости> ЖурналПосещаемости { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ЖурналУспеваемости> ЖурналУспеваемости { get; set; }
        public virtual Класс Класс { get; set; }
        public virtual Родители Родители { get; set; }
    }
}
